# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

"""Tests for TurnoverCalendar iCal generation."""

from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo

from custom_components.turnovercal.calendar import generate_ical
from custom_components.turnovercal.models import TurnoverEvent

UTC = ZoneInfo("UTC")
ET = ZoneInfo("America/New_York")
VALID_UID = "0123456789abcdef@turnovercal.homeassistant"
VALID_UID_2 = "abcdef0123456789@turnovercal.homeassistant"


def _make_event(
    uid: str = VALID_UID,
    *,
    dtstart: datetime | None = None,
    dtend: datetime | None = None,
    is_trailing: bool = False,
) -> TurnoverEvent:
    """Create a TurnoverEvent for testing."""
    return TurnoverEvent(
        uid=uid,
        summary="Turnover - Beach House",
        dtstart=dtstart or datetime(2026, 3, 10, 11, 0, tzinfo=ET),
        dtend=dtend or datetime(2026, 3, 10, 15, 0, tzinfo=ET),
        timezone="America/New_York",
        source_checkout_id="src-co-001",
        source_checkin_id=None if is_trailing else "src-ci-002",
        created_at=datetime(2026, 3, 1, 12, 0, tzinfo=UTC),
        is_trailing=is_trailing,
    )


# ---------------------------------------------------------------------------
# VCALENDAR properties
# ---------------------------------------------------------------------------


class TestVCalendarProperties:
    """Tests for VCALENDAR-level properties."""

    def test_prodid(self) -> None:
        """VCALENDAR PRODID is -//Home Assistant//TurnoverCal//EN."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "PRODID:-//Home Assistant//TurnoverCal//EN" in text

    def test_version(self) -> None:
        """VCALENDAR VERSION is 2.0."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "VERSION:2.0" in text

    def test_calscale(self) -> None:
        """VCALENDAR CALSCALE is GREGORIAN."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "CALSCALE:GREGORIAN" in text

    def test_method(self) -> None:
        """VCALENDAR METHOD is PUBLISH."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "METHOD:PUBLISH" in text

    def test_x_wr_calname(self) -> None:
        """VCALENDAR X-WR-CALNAME uses prefix and property name."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "X-WR-CALNAME:Turnover - Beach House" in text

    def test_x_wr_timezone(self) -> None:
        """VCALENDAR X-WR-TIMEZONE uses configured timezone."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "X-WR-TIMEZONE:America/New_York" in text


# ---------------------------------------------------------------------------
# VTIMEZONE
# ---------------------------------------------------------------------------


class TestVTimezone:
    """Tests for VTIMEZONE generation."""

    def test_vtimezone_present_with_events(self) -> None:
        """VTIMEZONE is present when events use TZID."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "BEGIN:VTIMEZONE" in text
        assert "TZID:America/New_York" in text

    def test_vtimezone_auto_generated(self) -> None:
        """VTIMEZONE is auto-generated by icalendar library."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "END:VTIMEZONE" in text


# ---------------------------------------------------------------------------
# VEVENT properties
# ---------------------------------------------------------------------------


class TestVEventProperties:
    """Tests for VEVENT-level properties."""

    def test_uid(self) -> None:
        """VEVENT UID matches the TurnoverEvent uid."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert f"UID:{VALID_UID}" in text

    def test_dtstamp(self) -> None:
        """VEVENT DTSTAMP is present as UTC."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "DTSTAMP:" in text

    def test_dtstart_with_tzid(self) -> None:
        """VEVENT DTSTART uses TZID parameter."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "DTSTART;TZID=America/New_York:" in text

    def test_dtend_with_tzid(self) -> None:
        """VEVENT DTEND uses TZID parameter."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "DTEND;TZID=America/New_York:" in text

    def test_summary(self) -> None:
        """VEVENT SUMMARY matches the TurnoverEvent summary."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "SUMMARY:Turnover - Beach House" in text

    def test_description(self) -> None:
        """VEVENT DESCRIPTION is present."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "DESCRIPTION:Cleaning window between guests" in text

    def test_status(self) -> None:
        """VEVENT STATUS is CONFIRMED."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "STATUS:CONFIRMED" in text


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestICalEdgeCases:
    """Tests for iCal generation edge cases."""

    def test_empty_calendar_valid(self) -> None:
        """Empty event list produces valid VCALENDAR with no VEVENT."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert "BEGIN:VCALENDAR" in text
        assert "END:VCALENDAR" in text
        assert "BEGIN:VEVENT" not in text

    def test_multiple_events(self) -> None:
        """Multiple events produce multiple VEVENT blocks."""
        evt1 = _make_event(VALID_UID)
        evt2 = _make_event(
            VALID_UID_2,
            dtstart=datetime(2026, 3, 15, 11, 0, tzinfo=ET),
            dtend=datetime(2026, 3, 15, 15, 0, tzinfo=ET),
        )
        data = generate_ical(
            events=[evt1, evt2],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        text = data.decode("utf-8")
        assert text.count("BEGIN:VEVENT") == 2
        assert text.count("END:VEVENT") == 2

    def test_summary_uses_configured_prefix(self) -> None:
        """Summary uses the configured prefix per FR-014."""
        evt = _make_event()
        data = generate_ical(
            events=[evt],
            timezone_str="America/New_York",
            summary_prefix="Clean",
            property_name="Lake Cabin",
        )
        text = data.decode("utf-8")
        # The X-WR-CALNAME should use the prefix
        assert "X-WR-CALNAME:Clean - Lake Cabin" in text

    def test_output_is_bytes(self) -> None:
        """generate_ical returns bytes."""
        data = generate_ical(
            events=[],
            timezone_str="America/New_York",
            summary_prefix="Turnover",
            property_name="Beach House",
        )
        assert isinstance(data, bytes)
